### ISSUE TITLE
Replace `nginx` build order after re-architecture

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/web-servers#129]
## Describe the Enhancement

[RFC 0007](https://github.com/paketo-buildpacks/rfcs/blob/main/text/web-servers/0007-web-servers-rearchitecture.md) has been approved and merged.

## Possible Solution

The currently existing `nginx` build orders need to be replaced with the following.
### NPM Frontend
```toml
[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/node-engine"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"

  [[order.group]]
    id = "paketo-buildpacks/nginx"

  [[order.group]]
    id = "paketo-buildpacks/nginx-zero-configuration"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/nginx-start"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
```
### Yarn Frontend
```toml
[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/node-engine"

  [[order.group]]
    id = "paketo-buildpacks/yarn"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"

  [[order.group]]
    id = "paketo-buildpacks/nginx"

  [[order.group]]
    id = "paketo-buildpacks/nginx-zero-configuration"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/nginx-start"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
```
### Standard
```toml
[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/nginx-dist"

  [[order.group]]
    id = "paketo-buildpacks/nginx-zero-configuration"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/nginx-start"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
```

## Motivation

This is part of https://github.com/paketo-buildpacks/web-servers/issues/128
